###########################################################################
# Copyright 2021 IoT.bzh
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###########################################################################

Name:       platform-info-binding
#Hexsha: e6adcb749446d0512800c0950784be2008972923
Version: 9.0.2
Release: 12%{?dist}
License:    GPL-3.0-only
Summary:    Platform info API for catch useful information
URL:        https://github.com/redpesk-common/platform-info-binding
Source0:    %{name}-%{version}.tar.gz

%global _afmappdir %{_prefix}/redpesk

Requires: platform-runtime-tools

BuildRequires: cmake
BuildRequires: gcc gcc-c++
BuildRequires: pkgconfig(json-c)
BuildRequires: pkgconfig(afb-binding)
BuildRequires: pkgconfig(afb-helpers4)
BuildRequires: pkgconfig(librp-utils-json-c)
BuildRequires: pkgconfig(libudev)

%description
The platform info binding implement an API which read files generated by platform-runtime-tools and gives platform informations

%prep
%autosetup -p 1

%build
%cmake .  -DAFM_APP_DIR=%{_afmappdir}
%cmake_build

%install
%cmake_install

%files
%dir %{_afmappdir}
%dir %{_afmappdir}/%{name}
%{_afmappdir}/%{name}

%changelog
* Mon Mar 31 2025 jobol <jobol@iot.bzh> 1.4.1
- remove afm-rpm-macros

* Thu Apr 15 2021 IoT.bzh(iotpkg) <redpesk.list@iot.bzh> 1.4.0
- Upgrade version from source commit sha: fb805b757aff5b278c3b68b48ffa38e7cf0ec335
- Commit message:
- 	adding list of plugins installed
- 	
- 	Signed-off-by: vlefebvre <valentin.lefebvre@iot.bzh>


* Wed Mar 31 2021 IoT.bzh(iotpkg) <redpesk.list@iot.bzh> 1.3.1
- Upgrade version from source commit sha: e009b5308d67de3578c2a28454c6de9ebb7dd5c2
- Commit message:
- 	Updating scripts for list packages
- 	
- 	Signed-off-by: Valentin Lefebvre <valentin.lefebvre@iot.bzh>


* Tue Mar 30 2021 IoT.bzh(iotpkg) <redpesk.list@iot.bzh> 1.3.0
- Upgrade version from source commit sha: 91447309342767eac046b59cee9c5f56a7ea8260
- Commit message:
- 	Updating scripts for list packages
- 	
- 	Signed-off-by: Valentin Lefebvre <valentin.lefebvre@iot.bzh>


* Fri Mar 26 2021 IoT.bzh(iotpkg) <redpesk.list@iot.bzh> 1.2.0
- Upgrade version from source commit sha: eca6e9fcac6ee9c06ba01c87b1040b6664db3746
- Commit message:
- 	Remove list of packages installed from get_all_info verb
- 	
- 	Signed-off-by: Valentin Lefebvre <valentin.lefebvre@iot.bzh>


* Tue Mar 23 2021 IoT.bzh(iotpkg) <redpesk.list@iot.bzh> 1.1.0
- Upgrade version from source commit sha: a4dd9b8a2e58aa19f592f06d4b66feb102a978c1
- Commit message:
- 	Fix afm packages version
- 	
- 	Signed-off-by: Valentin Lefebvre <valentin.lefebvre@iot.bzh>


* Thu Mar 11 2021 IoT.bzh(iotpkg) <redpesk.list@iot.bzh> 1.0.0
- Upgrade version from source commit sha: ab6a613cc88981d6a96594031affcaf31d24c895
- Commit message:
- 	Script path during installation
- 	
- 	Signed-off-by: Valentin Lefebvre <valentin.lefebvre@iot.bzh>


* Tue Mar 09 2021 IoT.bzh(iotpkg) <redpesk.list@iot.bzh> 10.93.0+20210309+1+g4bfbea0
- Upgrade version from source commit sha: 4bfbea00177dd04cc5e9894d288431b5aa217c20
- Commit message:
- 	add scripts features to dynamicals informations
- 	
- 	Signed-off-by: Valentin Lefebvre <valentin.lefebvre@iot.bzh>


* Mon Mar 08 2021 IoT.bzh(iotpkg) <redpesk.list@iot.bzh> 10.93.0
- Upgrade version from source commit sha: 0def5c78e35fa88d71b22d46023e84b549bab4e2
- Commit message:
- 	Fix & add tests
- 	
- 	-Fix the previous tests for subscribe/unsubscribe verbs.
- 	Now the calls for these verbs should contain at least
- 	'event':'target-event'('monitor-devices' in this case)
- 	to be considered successful.
- 	-Add new test for new verb 'scan' with no filter & mask.
- 	
- 	Signed-off-by: Farshid Monhaseri <monhaseri.f@gmail.com>
- 	Change-Id: I6b0b28b4a2221b774ce7476d947482745ce01ddf


